# Generated by Django 4.2.8 on 2023-12-04 22:27

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=events.models.upload_to
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("artworks", models.ManyToManyField(blank=True, to="artworks.artwork")),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "default_related_name": "events",
            },
        ),
    ]
