# Generated by Django 4.2.8 on 2023-12-04 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="slug",
        ),
    ]
