# Generated by Django 4.2.8 on 2024-01-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
        ("events", "0002_remove_event_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location",
        ),
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared.address",
            ),
        ),
    ]
