# Generated by Django 4.2.8 on 2024-01-31 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
        ("events", "0003_remove_event_location_event_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="shared.address",
            ),
        ),
    ]
