version: '3.7'
services:
  api:
    image: "artfeelz-api:dev"
    build:
      target: development_build
      context: .
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16.1
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5433
    env_file:
      - ./.env.dev

volumes:
  postgres_data:
  superset_postgres_data:
