# Generated by Django 4.2.8 on 2023-12-04 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="slug",
        ),
    ]
