# Generated by Django 4.2.8 on 2024-01-24 20:27

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "city_district",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=100, null=True)),
                ("road", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "house_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("suburb", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "default_related_name": "addresses",
            },
        ),
    ]
