name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
     postgres:
        image: postgres:16.1
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U test_user" --health-interval=10s --health-timeout=5s --health-retries=3


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Run Tests
        uses: actions/setup-python@v4
        env:
          DEBUG: True
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: poetry run python manage.py test

      - name: Build and push Docker image
        env:
          IMAGE_TAG: dev
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/artemote-api:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/artemote-api:${IMAGE_TAG}
