name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Run Tests
        run: python manage.py test

      - name: Build and push Docker image
        env:
          IMAGE_TAG: dev
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/artemote-api:${IMAGE_TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/artemote-api:${IMAGE_TAG}
